Grace-Shopper-Proj/ramen

- .gitignore
- package-lock.json
- server/db/models/index.js
- server/db/models/product.js
> product model complete

- server/db/models/index.js
- server/db/models/product.spec.js
Created test specs for the Product model.
> product model tests

- norm.md
- package-lock.json
- package.json
- server/db/models/product.spec.js
- server/db/models/user.js
- server/db/models/user.spec.js
We created a model for users and wrote tests for the model.
> User models

- seed.js
- server/db/models/product.js
- server/db/models/product.spec.js
> fixed product model and tested

- category_data.js
- package.json
- script/seed.js
- server/api/ingredients.js
- server/db/db.js
- server/db/models/category.js
- server/db/models/index.js
> fixed seed file, needs association

- ingredients_data.js
- script/seed.js
- server/api/ingredients.js
- server/db/db.js
assigned associations inside the seed file
> Backend product 14

- client/components/OrderPage.js
> fixed some stupid bugs in React

- client/components/OrderPage.js
> more stupid bugs

- client/store/index.js
> updated store

- client/components/SingleSelectionForm.js
> fixed typo

- client/components/DietaryRestrictionForm.js
- client/components/OrderPage.js
- client/components/SingleSelectionForm.js
- client/store/index.js
- client/store/product.js
- package-lock.json
- public/index.html
> Fixedsomebugs

- server/api/users.js
- server/api/users.spec.js
- server/db/models/user.js
- created route tests
- implemented GET, POST and DELETE routes
- added a new field to the User model: username
> implemented user routes and modified user model

- script/seed.js
- server/db/models/bowl.js
- server/db/models/index.js
> Feature (Model): Added a Bowl model

- server/db/models/bowl.js
> Fixed (Model): added a price field for the Bowl Model

- script/seed.js
- server/api/bowls.js
- server/api/index.js
- server/api/orders.js
- server/db/models/bowl.js
- server/db/models/index.js
- server/db/models/order.js
-- created order model 
-- fixed typo in bowls model
-- associated orders and bowls (one to many)
> feature(model): creates model for order

- client/AccountManagement.js
- client/app.js
- client/components/navbar.js
- server/index.js
- Create a skeleton of the Account Management page
- Add some React routes for the Order Page and the Account Management page (see app.js)
- Move the NavBar and Routes views to the top (so that now the login view is on the top; see app.js)
> Implement account management view

- client/app.js
- client/components/Cart.js
- client/components/CurrentBowl.js
- client/components/OrderPage.js
- client/routes.js
- public/style.css
- server/db/db.js
> Sumbit bowl66

- server/db/models/order.js
> Add promo code

- client/app.js
- client/components/AccountManagement.js
- client/components/CurrentBowl.js
- client/components/OrderPage.js
- client/routes.js
- server/api/bowls.js
- server/db/db.js
- server/db/models/bowl.js
- server/db/models/index.js
> Bowl price

- client/components/CurrentBowl.js
- client/components/DietaryRestrictionForm.js
- client/components/MultiSelectionForm.js
> fix(front-end): price

- client/app.js
- server/api/users.js
- server/api/users.spec.js
- server/db/models/index.js
- server/db/models/session.js
- server/db/models/user.js
> removed username in files

- server/db/models/index.js
> Line removal

- server/api/users.js
- server/db/models/user.js
> get all order routes

- client/app.js
- client/components/adminAllProducts.js
- client/components/adminPage.js
- client/components/ingredientForm.js
Prepopulates
Still need to add add and edit features
> Ingredient Form for admins

- client/components/OrderPage.js
- client/components/adminAllProducts.js
- client/components/ingredientForm.js
- client/store/product.js
- server/api/ingredients.js
- server/db/models/ingredient.js
- admin can see all the ingredients displayed and can edit them. 
Still to do:
> feature(front-end): creates admin edit page for products

- client/components/ManageUsers.js
- client/components/UserItem.js
- client/components/adminPage.js
- server/api/users.js
- server/db/models/user.js
- You should be able to see the user management component on the admin page.
- GET all users and PUT one user routes now check req.user to see if the request is made by authorized user.
- To make sure the new stuff works on your computer: change your own account to 'admin' in your local database!
> Implement user management

- client/components/ManageUsers.js
- client/components/UserItem.js
- server/api/users.js
The "upgrade to admin" button and "ban/un-ban" button should be working now.
> fix buttons in user management component

- client/components/CurrentBowl.js
- client/components/OrderPage.js
- client/components/SingleSelectionForm.js
- client/components/ingredientCard.js
- client/components/singleIngredient.js
- public/index.html
- public/style.css
- Added bootstrap
- began to style home page 
- Fixed checkout button logic so that it will only be enabled when an item from each category is selected (switched and logic to or logic)
> feature(style): adding bootstrap, styling home page

- client/components/AccountManagement.js
- client/components/navbar.js
- client/store/index.js
- client/store/order.js
- client/store/pastOrders.js
- server/api/orders.js
- server/db/models/order.js
things are working i just have to add some connections
> User account information page working and updated the Order model. 

- client/components/ingredientForm.js
- package-lock.json
- server/api/ingredients.js
added delete functionality to the admin ingredient page.
> fix(front-end and routes): allows admin to delete ingredients

- client/components/AccountManagement.js
- client/components/OrderPage.js
- client/components/reviews/ReviewList.js
- client/components/reviews/reviewForm.js
- client/store/pastReview.js
- public/style.css
- server/api/reviews.js
- server/api/users.js
- server/db/db.js
> Feature (routes): Added the delete review route

- client/store/pastOrders.js
- script/seed.js
- server/db/models/order.js
> Updated seed file with fake bowl order review and user

- client/components/ManageReviews.js
- client/components/adminPage.js
- client/components/ingredientForm.js
- client/store/review.js
- server/api/bowls.js
- server/api/reviews.js
- fixed route so that it sends the status
- wrote thunk
- implemented delete button
> feature(reviews): allowing admin to delete reviews

- client/components/Cart.js
- client/components/CheckoutForm.js
- package-lock.json
- package.json
- public/index.html
- server/charge/index.js
- server/index.js
Cart page has a payment form but it's not working.
> implement parts of checkout

- package-lock.json
> added an image folder

- server/db/models/order.js
- updated the order model to remove the quantity and total price
- reverted the get price method to it's former version
> fix(models): removed quantity and total from order model

- client/components/reviews/ReviewList.js
- client/components/reviews/reviewForm.js
- client/store/review.js
- server/api/reviews.js
> Fixed (front-end) ReviewList shows the newest review #144

- server/db/models/ingredient.js
- server/db/models/ingredient.spec.js
> Method inventory147

- server/api/authorize.js
- server/api/orders.js
- server/api/reviews.js
> Secure routes

- client/app.js
- client/components/adminPage.js
- client/routes.js
- I re-organized the front end routes. My intention was not to change any functionality, so let me know if I accidentally did so.
> refractor(front-end routes): refractored front end routes

- client/components/OrderPage.js
- client/components/ingredientCard.js
- just a few changes to columns widths not crucial.
> feature(layout): modifies column size and spacing

- client/components/AccountManagement.js
- client/components/AccountManagement.specs.js
- server/api/orders.js
> fix past order component in account management view

- client/components/adminPage.js
- script/seed.js
> Admin page

- client/components/DietaryRestrictionForm.js
- client/components/ManageOrders.js
- client/components/MultiSelectionForm.js
- client/components/UserItem.js
- client/components/ingredientForm.js
- public/index.html
- public/style.css
- server/db/models/order.js
> Finished cleaning up everything and everything is working

- script/seed.js
fish is not vege according to Cindy.
> changed seed file

- README.md
> add link to deployed app to readme
